local Unlocker, Caffeine, Project = ...

local SpellBook = Caffeine.Globals.SpellBook

print("Im in the real spellbook!")

Project.Spells = {

    corruption = SpellBook:GetSpell(47813),
    curse_of_agony = SpellBook:GetSpell(47864),
    curse_of_doom = SpellBook:GetSpell(47867),
    curse_of_tongues = SpellBook:GetSpell(11719),
    curse_of_weakness = SpellBook:GetSpell(50511),
    curse_of_the_elements = SpellBook:GetSpell(47865),
    death_coil = SpellBook:GetSpell(47860),
    drain_life = SpellBook:GetSpell(47857),
    drain_mana = SpellBook:GetSpell(5138),
    drain_soul = SpellBook:GetSpell(47855),
    fear = SpellBook:GetSpell(6215),
    howl_of_terror = SpellBook:GetSpell(17928),
    life_tap = SpellBook:GetSpell(57946),
    seed_of_corruption = SpellBook:GetSpell(47836),
    banish = SpellBook:GetSpell(18647),
    challenging_howl = SpellBook:GetSpell(59671),
    create_firestone = SpellBook:GetSpell(60220),
    create_healthstone = SpellBook:GetSpell(47878),
    create_soulstone = SpellBook:GetSpell(47884),
    create_spellstone = SpellBook:GetSpell(47888),
    demon_armor = SpellBook:GetSpell(47889),
    demon_charge = SpellBook:GetSpell(54785),
    demon_skin = SpellBook:GetSpell(696),
    demonic_circle_summon = SpellBook:GetSpell(48018),
    demonic_circle_teleport = SpellBook:GetSpell(48020),
    demonic_empowerment = SpellBook:GetSpell(47193),
    detect_invisibility = SpellBook:GetSpell(132),
    eye_of_kilrogg = SpellBook:GetSpell(126),
    fel_armor = SpellBook:GetSpell(47893),
    fel_domination = SpellBook:GetSpell(18708),
    health_funnel = SpellBook:GetSpell(47856),
    immolation_aura = SpellBook:GetSpell(50589),
    inferno = SpellBook:GetSpell(1122),
    metamorphosis = SpellBook:GetSpell(47241),
    ritual_of_doom = SpellBook:GetSpell(18540),
    ritual_of_souls = SpellBook:GetSpell(58887),
    ritual_of_summoning = SpellBook:GetSpell(698),
    sense_demons = SpellBook:GetSpell(5500),
    shadow_cleave = SpellBook:GetSpell(50581),
    shadow_ward = SpellBook:GetSpell(47891),
    soul_link = SpellBook:GetSpell(19028),
    soulshatter = SpellBook:GetSpell(29858),
    subjugate_demon = SpellBook:GetSpell(61191),
    summon_felguard = SpellBook:GetSpell(30146),
    summon_felhunter = SpellBook:GetSpell(691),
    summon_imp = SpellBook:GetSpell(688),
    summon_incubus = SpellBook:GetSpell(713),
    summon_succubus = SpellBook:GetSpell(712),
    summon_voidwalker = SpellBook:GetSpell(697),
    unending_breath = SpellBook:GetSpell(5697),
    hellfire = SpellBook:GetSpell(47823),
    immolate = SpellBook:GetSpell(47811),
    incinerate = SpellBook:GetSpell(47838),
    rain_of_fire = SpellBook:GetSpell(47820),
    searing_pain = SpellBook:GetSpell(47815),
    shadow_bolt = SpellBook:GetSpell(47809),
    shadowflame = SpellBook:GetSpell(61290),
    soul_fire = SpellBook:GetSpell(47825),
    shadow_bolt_buff = SpellBook:GetSpell(17800),
}


